name: TimedWhitelist
version: '${project.version}'
main: cf.towsifkafi.timedwhitelist.Timedwhitelist
api-version: 1.18
authors: [ TowsifKafi ]
description: A Whitelisting plugin that will automaticly prevent an player from joining after a specific time
